name: MAIL
on:
  schedule:
    - cron: "50 6 * * *"
jobs:
  build:
    name: building
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python mail.py
        
